# Generated by Django 2.1.5 on 2019-07-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyvolunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='codeNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='phoneNum',
            field=models.IntegerField(null=True),
        ),
    ]
