# Generated by Django 2.1.5 on 2019-07-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyvolunteer', '0005_auto_20190718_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organ',
            name='image',
        ),
    ]
