# Generated by Django 2.1.5 on 2019-07-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyvolunteer', '0006_remove_organ_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='another',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='기타 특이사항'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_area', to='easyvolunteer.Area', verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='codeNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='주민번호'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='is_organ',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_job', to='easyvolunteer.Job', verbose_name='직업ㄴ'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='license',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='자격증'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='phoneNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='crew',
            field=models.CharField(max_length=20, verbose_name='소속'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='head',
            field=models.CharField(max_length=20, verbose_name='책임자명'),
        ),
    ]
