# Generated by Django 2.2.3 on 2019-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyvolunteer', '0008_auto_20191126_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
