# Generated by Django 2.2.3 on 2019-11-26 13:23

from django.db import migrations
import easyvolunteer.models


class Migration(migrations.Migration):

    dependencies = [
        ('easyvolunteer', '0010_auto_20191126_1316'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cuser',
            managers=[
                ('objects', easyvolunteer.models.UserManager()),
            ],
        ),
    ]
