# Generated by Django 2.2.3 on 2019-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyvolunteer', '0011_auto_20191126_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='이름'),
        ),
    ]
